baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Yonatan Teklezgi'
theme = "tophat"

[params]
    
  subtitle = "Veille technologique"
  description = "Veille technologique"
  author = "Yonatan Teklezgi"

  main = "post"
  featured = true
  
  # You can customize the visibility of some elements like date, reading time, words counter and tags inside article by setting true or false
  show_date_on_article = true
  show_reading_time_on_article = true
  show_words_count_on_article = true
  show_tags_on_article = true  

  [menu]

  [[menu.main]]
    identifier = "apropos"
    name = "A propos"
    url = "pages/apropos/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "pages/contact/"    
  


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

